# render.yaml

services:
  - type: web
    name: silmedy-web-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: FIREBASE_CREDENTIAL_PATH
        sync: false
      - key: FIREBASE_DB_URL
        sync: false