name: Deploy Backend (Docker on EC2)

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1) 리포지토리 체크아웃
      - name: Checkout 코드
        uses: actions/checkout@v4

      # 2) SSH 키 설정
      - name: SSH 키 세팅
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 3) known_hosts에 EC2 호스트 추가
      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 4) EC2에서 배포 스크립트 실행 (Docker)
      - name: EC2에 배포 스크립트 실행
        uses: appleboy/ssh-action@v0.1.6
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # 1) 백엔드 프로젝트 디렉토리로 이동
            cd ~/silmedy-web-server

            # 2) 최신 코드 가져오기
            git pull origin main

            # 3) 기존 프로덕션 컨테이너 정지 · 삭제
            docker stop silmedy_prod_container || true
            docker rm   silmedy_prod_container || true

            # 4) 사용하지 않는 이미지·볼륨 일괄 제거
            docker image prune -a -f

            # 5) 캐시 없이 새 이미지 빌드
            docker build --no-cache -t silmedy_prod .

            # 6) 새 컨테이너 실행
            docker run -d \
              --env-file ./secrets/.env \
              -p 5000:5000 \
              --name silmedy_prod_container \
              --restart unless-stopped \
              silmedy_prod

            # 7) (선택) 컨테이너 상태 확인
            docker ps --filter "name=silmedy_prod_container"
