name: Deploy Backend via Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Build & Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/silmedy-web-server

            # Git pull (optional if you rsync instead)
            git pull origin main

            # 컨테이너 재빌드
            docker stop silmedy_prod_container || true
            docker rm   silmedy_prod_container || true
            docker image prune -a -f
            docker build --no-cache -t silmedy_prod .

            # 마운트(또는 COPY) 된 secrets/.env, secrets/firebase-service-account.json 사용
            docker run -d \
              --name silmedy_prod_container \
              --env-file ./.env \
              -p 5000:5000 \
              --restart unless-stopped \
              silmedy_prod
