name: Deploy Backend (SSH & Rsync & PM2)

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) SSH 에이전트 실행 및 키 로드
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 3) EC2 호스트를 known_hosts에 등록
      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 4) 로컬 코드 → EC2 동기화
      - name: Sync code to EC2 via rsync
        run: |
          rsync -avz --delete \
            . \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/silmedy-web-server

      # 5) EC2 접속 후 서비스 재시작
      - name: Restart service on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd ~/silmedy-web-server

            # Python 가상환경 생성·의존성 설치
            if [ ! -d .venv ]; then
              python3 -m venv .venv
            fi
            source .venv/bin/activate
            pip install -r requirements.txt

            # FastAPI 앱 실행 또는 재시작
            pm2 restart silmedy-web-server --update-env \
              || pm2 start uvicorn --name silmedy-web-server --interpreter python3 -- silmedi.main:app --host 0.0.0.0 --port 5000
