name: Deploy Backend via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy-backend-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sync code to EC2 via rsync
        run: |
          rsync -avz --delete \
            . \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/silmedy-web-server

      - name: Deploy on EC2 via Docker
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd ~/silmedy-web-server

            # 기존 컨테이너 정지·삭제
            docker stop silmedy_prod_container || true
            docker rm   silmedy_prod_container || true

            # 사용하지 않는 이미지 정리
            docker image prune -a -f

            # Dockerfile 이 이 위치에 있어야 합니다!
            docker build --no-cache -t silmedy_prod .
            docker run -d \
              --env-file ./secrets/.env \
              -p 5000:5000 \
              --name silmedy_prod_container \
              --restart unless-stopped \
              silmedy_prod

            # (선택) 헬스체크
            docker ps --filter "name=silmedy_prod_container"
